/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const TicketPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'provider' : IDL.Null,
  'customer' : IDL.Null,
});
export const TicketStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'closed' : IDL.Null,
  'in_progress' : IDL.Null,
  'open' : IDL.Null,
});
export const Time = IDL.Int;
export const Ticket = IDL.Record({
  'id' : IDL.Text,
  'status' : TicketStatus,
  'title' : IDL.Text,
  'moduleName' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'customerId' : IDL.Principal,
  'priority' : TicketPriority,
  'attachment' : IDL.Opt(ExternalBlob),
});
export const TicketComment = IDL.Record({
  'id' : IDL.Text,
  'authorId' : IDL.Principal,
  'createdAt' : Time,
  'ticketId' : IDL.Text,
  'message' : IDL.Text,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : UserRole,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createTicket' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, TicketPriority, IDL.Opt(ExternalBlob)],
      [IDL.Text],
      [],
    ),
  'createUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
  'getAllTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
  'getCommentsByTicket' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TicketComment)],
      ['query'],
    ),
  'getTicketsByCustomer' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
  'getUser' : IDL.Func([IDL.Principal], [User], ['query']),
  'updateTicketStatus' : IDL.Func([IDL.Text, TicketStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const TicketPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'provider' : IDL.Null,
    'customer' : IDL.Null,
  });
  const TicketStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'closed' : IDL.Null,
    'in_progress' : IDL.Null,
    'open' : IDL.Null,
  });
  const Time = IDL.Int;
  const Ticket = IDL.Record({
    'id' : IDL.Text,
    'status' : TicketStatus,
    'title' : IDL.Text,
    'moduleName' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'customerId' : IDL.Principal,
    'priority' : TicketPriority,
    'attachment' : IDL.Opt(ExternalBlob),
  });
  const TicketComment = IDL.Record({
    'id' : IDL.Text,
    'authorId' : IDL.Principal,
    'createdAt' : Time,
    'ticketId' : IDL.Text,
    'message' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createTicket' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, TicketPriority, IDL.Opt(ExternalBlob)],
        [IDL.Text],
        [],
      ),
    'createUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
    'getAllTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
    'getCommentsByTicket' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TicketComment)],
        ['query'],
      ),
    'getTicketsByCustomer' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
    'getUser' : IDL.Func([IDL.Principal], [User], ['query']),
    'updateTicketStatus' : IDL.Func([IDL.Text, TicketStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };