/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Ticket {
  'id' : string,
  'status' : TicketStatus,
  'title' : string,
  'moduleName' : string,
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : Time,
  'customerId' : Principal,
  'priority' : TicketPriority,
  'attachment' : [] | [ExternalBlob],
}
export interface TicketComment {
  'id' : string,
  'authorId' : Principal,
  'createdAt' : Time,
  'ticketId' : string,
  'message' : string,
}
export type TicketPriority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type TicketStatus = { 'resolved' : null } |
  { 'closed' : null } |
  { 'in_progress' : null } |
  { 'open' : null };
export type Time = bigint;
export interface User {
  'id' : Principal,
  'name' : string,
  'createdAt' : Time,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'provider' : null } |
  { 'customer' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addComment' : ActorMethod<[string, string], undefined>,
  'createTicket' : ActorMethod<
    [string, string, string, TicketPriority, [] | [ExternalBlob]],
    string
  >,
  'createUser' : ActorMethod<[string, string, UserRole], undefined>,
  'getAllTickets' : ActorMethod<[], Array<Ticket>>,
  'getCommentsByTicket' : ActorMethod<[string], Array<TicketComment>>,
  'getTicketsByCustomer' : ActorMethod<[], Array<Ticket>>,
  'getUser' : ActorMethod<[Principal], User>,
  'updateTicketStatus' : ActorMethod<[string, TicketStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];